{% set name = "cellpose" %}
{% set version = "0.1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9b77e1879425f8a80d419c9bb802c5badf2dd37e986e6fdb54806d045a849de5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py2]

requirements:
  host:
    - python
    - pip
    - numpy <=1.19.2
    - scipy
    - setuptools_scm
    - pytest-runner
    #- matplotlib <=3.3.2
    #- natsort
    #- numba
    #- pillow <=7.0.0
    #- scikit-image ==0.17.2
    #- tqdm

  run:
    - python
    - numpy <=1.19.1
    - scipy
    - matplotlib <=3.3.2
    - natsort
    - numba
    - pillow <=7.0.0
    #- scikit-image ==0.17.2
    - tqdm

test:
  imports:
    - cellpose

about:
  home: "https://github.com/MouseLand/cellpose"
  license: BSD
  summary: "anatomical segmentation algorithm"