{% set name = "cellpose" %}
{% set version = "0.0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 761c32774847f30f70aba4860fa04e47fc1cb22e541a8b381f0c07a8c985fcce

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py2]

requirements:
  host:
    - matplotlib
    - natsort
    - numba
    - numpy <=1.19.1
    - pillow <=7.0.0
    - pip
    - python
    - scikit-image
    - scipy
    - tqdm
    - mxnet-mkl
    - opencv-python-headless

  run:
    - matplotlib
    - natsort
    - numba
    - numpy <=1.19.1
    - pillow <=7.0.0
    - python
    - scikit-image
    - scipy
    - tqdm
    - mxnet-mkl
    - opencv-python-headless

test:
  imports:
    - cellpose

about:
  home: "https://github.com/MouseLand/cellpose"
  license: BSD
  summary: "anatomical segmentation algorithm"